blank_issues_enabled: false
contact_links:
  - name: ğŸ›  CDKTF Issues
    url: https://github.com/hashicorp/terraform-cdk/issues/new/choose
    about: "The majority of issues need to be resolved in the main cdktf codebase, so the best way to get ğŸ‘€ on those is to file them in the terraform-cdk repository."
  - name: â“ Question
    url: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47
    about: ğŸ™‹ For usage questions that may not require a core maintainer to answer, post in our community forum
  - name: ğŸ’¼ Terraform Cloud/Enterprise Troubleshooting
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues related to the Terraform Cloud/Enterprise platform, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
